name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze
        env:
          GITHUB_TOKEN: 0b744f5c-8cdf-44f5-9969-7ad6ce9a59ab
          SONAR_TOKEN: e62c84adbcfda79e46a9c096fbf892c15140994b
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=neojarvis-testing_0b744f5c-8cdf-44f5-9969-7ad6ce9a59ab
          -Dsonar.login=e62c84adbcfda79e46a9c096fbf892c15140994b
